version: "3.8"

services:
  database:
    image: postgres:15-alpine
    container_name: postgres_db
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - transcendence_net
    restart: unless-stopped

  backend:
    build: ./backend
    container_name: django_backend
    env_file:
      - .env
    depends_on:
      - database
    networks:
      - transcendence_net
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: react_frontend
    networks:
      - transcendence_net
    restart: unless-stopped

  nginx:
    build: ./nginx
    container_name: nginx_proxy
    ports:
      - "443:443"
    depends_on:
      - frontend
      - backend
    networks:
      - transcendence_net
    restart: unless-stopped

networks:
  transcendence_net:
    driver: bridge

volumes:
  db_data:
