services:
  database:
    image: postgres:15-alpine
    container_name: postgres_db
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - transcendence_net
    restart: unless-stopped

  backend:
    build: ./backend
    container_name: django_backend
    env_file:
      - .env
    volumes:
      - ./backend:/app
    depends_on:
      - database
    networks:
      - transcendence_net
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: react_frontend
    ports:
      - "5173:5173"
    networks:
      - transcendence_net
    restart: unless-stopped

  nginx:
    build: ./nginx
    container_name: nginx_proxy
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    networks:
      - transcendence_net
    restart: unless-stopped

  node_exporter:
    image: prom/node-exporter:latest
    container_name: node_exporter
    networks:
      - transcendence_net
    restart: unless-stopped

  prometheus:
      image: prom/prometheus:latest
      container_name: prometheus
      volumes:
        - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
        - prometheus_data:/prometheus
      networks:
        - transcendence_net
      restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    networks:
      - transcendence_net
    restart: unless-stopped

networks:
  transcendence_net:
    driver: bridge

volumes:
  db_data:
  prometheus_data:
  grafana_data: