events {}

http {
    server {
        # So far listening at port 80 (HTTP), SSL (443) to be done later
        listen 80;
        server_name localhost;

        # Everything that starts with /api/, send to Django container
        location /api/ {
            proxy_pass http://backend:8000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # Everything else goes to React container (Vite is running on port 5173)
        location / {
            proxy_pass http://frontend:5173;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
